apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-envoy
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-envoy
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443