apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flutter
spec:
  selector:
    app: {{ .Release.Name }}-flutter
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80