apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-maintemplate
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
{{- if .Values.domainSetup }}
    cert-manager.io/issuer: letsencrypt-prod
{{- end }}
spec:
{{- if .Values.domainSetup }}
  tls:
    - hosts:
      - maintemplate.{{ .Release.Name }}.getcouragenow.org
      secretName: maintemplate-{{ .Release.Name }}-tls
{{- end }}
  rules:  
  - http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-flutter
          servicePort: 80
        path: /*
      - backend:
          serviceName: {{ .Release.Name }}-envoy
          servicePort: 443
        path: /proto\.Broadcast*
{{- if .Values.domainSetup }}
    host: maintemplate.{{ .Release.Name }}.getcouragenow.org
{{- end }}