apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-maintemplate
  annotations:
    cloud.google.com/app-protocols: '{"http2":"HTTP2"}'
spec:
  selector:
    app: {{ .Release.Name }}-maintemplate
  type: NodePort
  ports:
  - name: http2
    port: 9074